### ISSUE TITLE
Issues with large Images

### ISSUE THREAD

**Issue by chonthu** [nf/dl#4]
Getting state error on large images.:

using:

`opts := &fetch.Options{Concurrency: 2, ErrorThreshold: 100}`

Example code:

```
opts := &fetch.Options{Concurrency: 2, ErrorThreshold: 100}
state, err := fetch.Fetch(r.LocalPath+"/"+path.Base(r.URL), r.URL, opts)
if err != nil {
    return err
}
for s := range state {
  if s.Error != nil {
    return s.Error
  }
}
```

Example url: 

`http://s3.amazonaws.com/stereogum.com/uploads/2016/03/sbr155-psychicills-300.jpg`

Great package BTW

**Comment by nf** [comment]
What's the error?

**Comment by chonthu** [comment]
Sorry, my mistake, my test was failing at something else, closing this out
